"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import type { CabinetStage, CabinetType, Project, ProjectCabinet } from "@/types/project";
import type { Personnel } from "@/types/work-plan";
import { createClient } from "@/lib/supabase/client";
import { formatDate } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from "@/components/ui/select";

const types:CabinetType[]=["T7","T9","T11","T21","T23"];
const stages:Record<CabinetStage,string>={cable:"Kablo",excavation_permit_waiting:"Kazı var · İzin alınmadı",excavation_waiting:"İzin alındı · Kazı yapılmadı",excavation_done:"Kazı yapıldı",energy_cable:"Enerji kablosu",energy:"Enerji",cabinet_installation:"Dolap kurulumu",joint:"Ek",transfer:"Aktarma"};
export function BgfdCabinetProgress({project,cabinets,personnel,readOnly}:{project:Project;cabinets:ProjectCabinet[];personnel:Personnel[];readOnly:boolean}){
 const router=useRouter(),[type,setType]=useState<CabinetType>("T7"),[count,setCount]=useState("1"),[selected,setSelected]=useState(cabinets[0]?.id??""),[stage,setStage]=useState<CabinetStage>("cable"),[leader,setLeader]=useState(""),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[info,setInfo]=useState("");
 const cabinet=cabinets.find(c=>c.id===selected);
 async function addCabinets(){const amount=Number(count);if(!Number.isInteger(amount)||amount<1||amount>100)return toast.error("Adet 1-100 arasında olmalı");const same=cabinets.filter(c=>c.cabinet_type===type),start=Math.max(0,...same.map(c=>c.cabinet_no))+1,{data:{user}}=await createClient().auth.getUser();const rows=Array.from({length:amount},(_,i)=>({project_id:project.id,cabinet_type:type,cabinet_no:start+i,name:`${type}-${start+i}`,tracks_excavation:project.tracks_excavation,created_by:user?.id}));const {error}=await createClient().from("project_cabinets").insert(rows);if(error)return toast.error("Dolaplar eklenemedi");toast.success(`${amount} adet ${type} dolap eklendi`);router.refresh()}
 async function save(){const p=personnel.find(x=>x.id===leader);if(!cabinet||!p)return toast.error("Dolap ve ekip başı seçin");if((stage==="energy_cable"||stage==="transfer")&&!info.trim())return toast.error("Bu aşamanın bilgi alanı zorunlu");const field=stage==="energy_cable"?{energy_cable_info:info.trim()}:stage==="transfer"?{transfer_info:info.trim()}:stage==="cable"?{cable_info:info.trim()||null}:{};const {data:{user}}=await createClient().auth.getUser();const {error}=await createClient().from("project_cabinet_progress").insert({cabinet_id:cabinet.id,stage,team_leader_personnel_id:p.id,team_leader_name:p.full_name,progress_date:date,created_by:user?.id,...field});if(error)return toast.error("Dolap ilerlemesi kaydedilemedi");setInfo("");toast.success(stage==="transfer"?"Aktarma tamamlandı":"İlerleme kaydedildi");router.refresh()}
 return <Card><CardHeader><CardTitle className="text-base">BGFD Dolap Takibi</CardTitle></CardHeader><CardContent className="space-y-5">
 {!readOnly&&<div className="grid gap-2 md:grid-cols-[1fr_1fr_auto]"><div><Label>Dolap türü</Label><Select value={type} onValueChange={v=>setType(v as CabinetType)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{types.map(t=><SelectItem key={t} value={t}>{t}</SelectItem>)}</SelectContent></Select></div><div><Label>Adet</Label><Input type="number" min="1" max="100" value={count} onChange={e=>setCount(e.target.value)}/></div><Button className="self-end" onClick={addCabinets}>Dolapları Ekle</Button></div>}
 {!cabinets.length?<p className="text-sm text-muted-foreground">Henüz dolap tanımlanmadı.</p>:<><div className="flex flex-wrap gap-2">{types.map(t=><span key={t} className="rounded-full bg-muted px-3 py-1 text-xs">{t}: {cabinets.filter(c=>c.cabinet_type===t).length}</span>)}</div><div><Label>İşlem yapılacak dolap</Label><Select value={selected} onValueChange={setSelected}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{cabinets.map(c=><SelectItem key={c.id} value={c.id}>{c.name}</SelectItem>)}</SelectContent></Select></div>
 {cabinet&&<div className="space-y-4 rounded-xl border p-4"><div><strong>{cabinet.name}</strong><p className="text-xs text-muted-foreground">{cabinet.cabinet_type} dolap · OBK uygulanmaz</p></div>{!readOnly&&<div className="grid gap-3 md:grid-cols-5"><div><Label>Süreç</Label><Select value={stage} onValueChange={v=>{setStage(v as CabinetStage);setInfo("")}}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{Object.entries(stages).filter(([k])=>!k.startsWith("excavation_")||cabinet.tracks_excavation).map(([k,v])=><SelectItem key={k} value={k}>{v}</SelectItem>)}</SelectContent></Select></div><div><Label>Ekip başı</Label><Select value={leader} onValueChange={setLeader}><SelectTrigger><SelectValue placeholder="Seçin"/></SelectTrigger><SelectContent>{personnel.map(p=><SelectItem key={p.id} value={p.id}>{p.full_name}</SelectItem>)}</SelectContent></Select></div><div><Label>Tarih</Label><Input type="date" value={date} onChange={e=>setDate(e.target.value)}/></div><div><Label>{stage==="energy_cable"?"Enerji kablo bilgisi":stage==="transfer"?"Aktarma bilgisi":"Kablo / açıklama"}</Label><Input value={info} onChange={e=>setInfo(e.target.value)} placeholder="Bilgi girin"/></div><Button className="self-end" onClick={save}>İlerleme Kaydet</Button></div>}
 <div className="space-y-2">{cabinet.progress.slice().sort((a,b)=>b.progress_date.localeCompare(a.progress_date)).map(p=><div key={p.id} className="grid gap-1 rounded-lg bg-muted/50 p-3 text-sm md:grid-cols-4"><strong>{stages[p.stage]}</strong><span>{p.team_leader_name}</span><span>{formatDate(p.progress_date)}</span><span>{p.energy_cable_info||p.transfer_info||p.cable_info||"—"}</span></div>)}</div></div>}</>}
 </CardContent></Card>
}
