"use client";
import { useEffect,useState,type ReactNode } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { Loader2,RotateCcw,Save } from "lucide-react";
import { toast } from "sonner";
import type { Project,ProjectStatus } from "@/types/project";
import type { Personnel } from "@/types/work-plan";
import { formatDateTime } from "@/lib/utils";
import { createClient } from "@/lib/supabase/client";
import { ProjectRepository } from "@/modules/projects/project-repository";
import { Button } from "@/components/ui/button";

type Props={projects:Project[];typeLabels:Record<string,string>;personnel:Personnel[];onDirtyChange?:(count:number)=>void};
const STATUSES:{value:ProjectStatus;label:string}[]=[{value:"waiting",label:"Başlamadı"},{value:"excavation_permit_waiting",label:"Kazı İzni Bekliyor"},{value:"in_progress",label:"Devam Ediyor"},{value:"completed",label:"Bitti"}];

export function EditableProjectsGrid({projects,typeLabels,personnel,onDirtyChange}:Props){
 const router=useRouter(),[rows,setRows]=useState(projects),[dirtyIds,setDirtyIds]=useState<Set<string>>(new Set()),[saving,setSaving]=useState(false);
 useEffect(()=>{setRows(projects);setDirtyIds(new Set());onDirtyChange?.(0)},[projects,onDirtyChange]);
 function mark(id:string,patch:Partial<Project>){setRows(current=>current.map(row=>row.id===id?{...row,...patch}:row));setDirtyIds(current=>{const next=new Set(current).add(id);onDirtyChange?.(next.size);return next})}
 function changeStatus(project:Project,status:ProjectStatus){mark(project.id,{status,current_team_leader_personnel_id:status==="in_progress"?project.current_team_leader_personnel_id:null,current_team_leader_name:status==="in_progress"?project.current_team_leader_name:null})}
 function changeLeader(project:Project,id:string){const person=personnel.find(item=>item.id===id);if(project.status==="completed")mark(project.id,{completed_by_personnel_id:id,completed_by_name:person?.full_name??null});else mark(project.id,{current_team_leader_personnel_id:id,current_team_leader_name:person?.full_name??null})}
 async function save(){const changed=rows.filter(row=>dirtyIds.has(row.id));for(const row of changed){if(row.status==="in_progress"&&!row.current_team_leader_personnel_id)return toast.error(`${row.project_code}: Devam eden proje için ekip başı seçin`);if(row.status==="completed"&&!row.completed_by_personnel_id&&row.project_type==="KURUMSAL_TTVPN")return toast.error(`${row.project_code}: Bitiren ekip başını seçin`)}setSaving(true);try{const repo=new ProjectRepository(createClient());for(const row of changed){const today=new Date().toISOString().slice(0,10);await repo.update(row.id,{status:row.status,current_team_leader_personnel_id:row.status==="in_progress"?row.current_team_leader_personnel_id:null,current_team_leader_name:row.status==="in_progress"?row.current_team_leader_name:null,completed_by_personnel_id:row.status==="completed"?row.completed_by_personnel_id:null,completed_by_name:row.status==="completed"?row.completed_by_name:null,completed_at:row.status==="completed"?row.completed_at||today:null,is_archived:row.status==="completed",archived_at:row.status==="completed"?row.archived_at||new Date().toISOString():null})}toast.success(`${changed.length} proje güncellendi`);setDirtyIds(new Set());onDirtyChange?.(0);router.refresh()}catch(error){console.error(error);toast.error("Projeler kaydedilemedi",{description:"Alt pafta veya dolapların tamamlandığını ve ekipbaşı seçimini kontrol edin."})}finally{setSaving(false)}}
 return <><div className="flex flex-col gap-3 border-b bg-muted/20 px-4 py-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-medium">Proje Takip Tablosu</p><p className="text-xs text-muted-foreground">Durumu değiştirin; Devam Ediyor veya Bitti ise ekipbaşını seçin.</p></div><div className="flex gap-2"><Button variant="outline" size="sm" disabled={!dirtyIds.size||saving} onClick={()=>{setRows(projects);setDirtyIds(new Set());onDirtyChange?.(0)}}><RotateCcw className="h-4 w-4"/>Geri Al</Button><Button size="sm" disabled={!dirtyIds.size||saving} onClick={save}>{saving?<Loader2 className="h-4 w-4 animate-spin"/>:<Save className="h-4 w-4"/>}Kaydet {dirtyIds.size?`(${dirtyIds.size})`:""}</Button></div></div><div className="overflow-x-auto"><table className="w-full min-w-[1150px] text-sm"><thead className="border-b bg-muted/40"><tr><Th>Tür</Th><Th>Proje Adı</Th><Th>Proje ID</Th><Th>Lokasyon</Th><Th>Durum</Th><Th>Ekip Başı</Th><Th>Proje Özeti</Th><Th>Son Güncelleme</Th></tr></thead><tbody>{rows.map(row=><tr key={row.id} className={`border-b ${dirtyIds.has(row.id)?"bg-primary/5":""}`}><Td>{typeLabels[row.project_type]??row.project_type}</Td><Td><Link href={`/projects/${row.id}`} className="font-medium text-primary hover:underline">{row.name}</Link></Td><Td>{row.project_code}</Td><Td>{row.project_type==="KURUMSAL_TTVPN"?row.location:"—"}</Td><Td><select className="h-9 w-full min-w-40 rounded-lg border bg-background px-2" value={row.status} onChange={event=>changeStatus(row,event.target.value as ProjectStatus)}>{STATUSES.map(status=><option key={status.value} value={status.value}>{status.label}</option>)}</select></Td><Td>{row.status==="in_progress"||row.status==="completed"?<select className="h-9 w-full min-w-44 rounded-lg border bg-background px-2" value={(row.status==="completed"?row.completed_by_personnel_id:row.current_team_leader_personnel_id)??""} onChange={event=>changeLeader(row,event.target.value)}><option value="">Ekip başı seçin</option>{personnel.map(person=><option key={person.id} value={person.id}>{person.full_name}</option>)}</select>:"—"}</Td><Td>{summary(row)}</Td><Td>{formatDateTime(row.updated_at)}</Td></tr>)}</tbody></table>{!rows.length&&<p className="p-10 text-center text-muted-foreground">Filtrelere uygun proje bulunamadı.</p>}</div></>
}
function summary(project:Project){if(project.project_type==="HP_ODAKLI")return `${project.sheet_numbers?.length??project.sheet_count??0} pafta · %${project.progress_percent??0}`;if(project.project_type==="BGFD")return "Dolap bazlı takip";return project.priority_order?`Öncelik ${project.priority_order}`:"Proje bazlı takip"}
function Th({children}:{children:ReactNode}){return <th className="px-4 py-3 text-left text-xs font-medium uppercase tracking-wide text-muted-foreground">{children}</th>}
function Td({children}:{children:ReactNode}){return <td className="px-4 py-3 align-middle">{children}</td>}
