"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { ChevronDown } from "lucide-react";
import { toast } from "sonner";
import type { HpSheetStatus,Project,ProjectSheet } from "@/types/project";
import type { Personnel } from "@/types/work-plan";
import { createClient } from "@/lib/supabase/client";
import { Button } from "@/components/ui/button";
import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from "@/components/ui/select";

const statuses:{value:HpSheetStatus;label:string;order:number}[]=[
 {value:"not_started",label:"Başlamadı",order:0},{value:"excavation_permit_waiting",label:"Kazı İzni Bekliyor",order:1},
 {value:"in_progress",label:"Devam Ediyor",order:2},{value:"completed",label:"Bitti",order:3},
];
export function HpFocusedSheetManager({project,sheets,personnel,readOnly}:{project:Project;sheets:ProjectSheet[];personnel:Personnel[];readOnly:boolean}){
 const router=useRouter(),[adding,setAdding]=useState(false);
 const sorted=[...sheets].sort((a,b)=>(statuses.find(s=>s.value===a.manual_status)?.order??0)-(statuses.find(s=>s.value===b.manual_status)?.order??0)||(a.sheet_no??a.name).localeCompare(b.sheet_no??b.name,"tr"));
 const totalHp=sheets.reduce((sum,sheet)=>sum+(sheet.hp_count??0),0),completedHp=sheets.reduce((sum,sheet)=>sum+(sheet.manual_status==="completed"?(sheet.hp_count??0):0),0);
 async function addSheet(){const client=createClient(),{data:{user}}=await client.auth.getUser();const {error}=await client.from("project_sheets").insert({project_id:project.id,name:`Pafta ${sheets.length+1}`,sheet_no:`Pafta ${sheets.length+1}`,manual_status:"not_started",tracks_cable:false,tracks_joint:false,tracks_obk:false,tracks_excavation:false,created_by:user?.id});if(error)return toast.error("Pafta eklenemedi");setAdding(false);router.refresh()}
 return <Card><CardHeader><CardTitle className="flex items-center justify-between gap-3 text-base"><span>HP Odaklı Paftalar</span><span className="text-blue-600">%{project.progress_percent??0}</span></CardTitle></CardHeader><CardContent className="space-y-4">
  <div className="grid gap-3 sm:grid-cols-3"><HpSummary label="Toplam HP" value={totalHp}/><HpSummary label="Tamamlanan HP" value={completedHp} completed/><HpSummary label="Kalan HP" value={Math.max(0,totalHp-completedHp)}/></div>
  <div className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full bg-blue-600 transition-all" style={{width:`${project.progress_percent??0}%`}}/></div>
  {!readOnly&&<div className="flex justify-end"><Button variant="outline" onClick={()=>setAdding(value=>!value)}>{adding?"Vazgeç":"Pafta Ekle"}</Button></div>}
  {adding&&<div className="rounded-xl border p-3"><p className="mb-2 text-sm text-muted-foreground">Yeni pafta oluşturulduktan sonra satırı açarak bilgilerini düzenleyebilirsiniz.</p><Button onClick={addSheet}>Yeni Paftayı Oluştur</Button></div>}
  <div className="overflow-hidden rounded-xl border"><div className="hidden grid-cols-[1fr_2fr_100px_170px_1fr_36px] gap-3 border-b bg-muted/50 px-4 py-2 text-xs font-semibold uppercase text-muted-foreground md:grid"><span>Pafta No</span><span>Adres</span><span>HP</span><span>Durum</span><span>Ekip Başı</span><span/></div>{sorted.map(sheet=><HpSheetRow key={sheet.id} sheet={sheet} personnel={personnel} readOnly={readOnly} onSaved={()=>router.refresh()}/>)}</div>
 </CardContent></Card>
}
function HpSummary({label,value,completed=false}:{label:string;value:number;completed?:boolean}){return <div className={`rounded-xl border p-4 ${completed?"border-blue-300 bg-blue-50 dark:border-blue-800 dark:bg-blue-950/40":"bg-muted/30"}`}><p className="text-xs text-muted-foreground">{label}</p><p className={`mt-1 text-2xl font-semibold ${completed?"text-blue-600 dark:text-blue-300":""}`}>{value.toLocaleString("tr-TR")}</p></div>}
function HpSheetRow({sheet,personnel,readOnly,onSaved}:{sheet:ProjectSheet;personnel:Personnel[];readOnly:boolean;onSaved:()=>void}){
 const [sheetNo,setSheetNo]=useState(sheet.sheet_no??sheet.name),[address,setAddress]=useState(sheet.address??""),[hp,setHp]=useState(sheet.hp_count??0),[notes,setNotes]=useState(sheet.notes??""),[status,setStatus]=useState<HpSheetStatus>(sheet.manual_status),[finisherId,setFinisherId]=useState(sheet.completed_by_personnel_id??""),[leaderId,setLeaderId]=useState(sheet.current_team_leader_personnel_id??""),[saving,setSaving]=useState(false);
 const meta=statuses.find(item=>item.value===sheet.manual_status),leaderName=sheet.manual_status==="completed"?sheet.completed_by_name:sheet.current_team_leader_name;
 async function save(){if(!sheetNo.trim())return toast.error("Pafta No zorunlu");if(status==="in_progress"&&!leaderId)return toast.error("Devam eden paftanın ekip başını seçin");if(status==="completed"&&!finisherId)return toast.error("Paftayı bitiren ekip başını seçin");const finisher=personnel.find(person=>person.id===finisherId),leader=personnel.find(person=>person.id===leaderId);setSaving(true);const {error}=await createClient().from("project_sheets").update({name:sheetNo.trim(),sheet_no:sheetNo.trim(),address:address.trim()||null,hp_count:Number(hp)||0,notes:notes.trim()||null,manual_status:status,is_completed:status==="completed",completed_at:status==="completed"?new Date().toISOString().slice(0,10):null,completed_by_personnel_id:status==="completed"?finisherId:null,completed_by_name:status==="completed"?finisher?.full_name:null,current_team_leader_personnel_id:status==="in_progress"?leaderId:null,current_team_leader_name:status==="in_progress"?leader?.full_name:null}).eq("id",sheet.id);setSaving(false);if(error)return toast.error("Pafta kaydedilemedi");toast.success("Pafta güncellendi");onSaved()}
 return <details className={`group border-b last:border-0 ${sheet.manual_status==="completed"?"bg-blue-50 dark:bg-blue-950/40":"bg-background"}`}><summary className="grid cursor-pointer list-none gap-2 px-4 py-3 md:grid-cols-[1fr_2fr_100px_170px_1fr_36px] md:items-center"><strong>{sheet.sheet_no||sheet.name}</strong><span className="truncate text-sm text-muted-foreground">{sheet.address||"—"}</span><span className="text-sm font-semibold">{(sheet.hp_count??0).toLocaleString("tr-TR")} HP</span><span className={`w-fit rounded-full px-2.5 py-1 text-xs font-semibold ${sheet.manual_status==="completed"?"bg-blue-600 text-white":"bg-muted"}`}>{meta?.label}</span><span className="truncate text-sm">{leaderName||"—"}</span><ChevronDown className="hidden h-4 w-4 transition-transform group-open:rotate-180 md:block"/></summary><div className="border-t bg-background/80 p-4"><div className="grid gap-3 md:grid-cols-2"><div><Label>Pafta No</Label><Input disabled={readOnly} value={sheetNo} onChange={event=>setSheetNo(event.target.value)}/></div><div><Label>HP Adedi</Label><Input disabled={readOnly} type="number" min="0" value={hp} onChange={event=>setHp(Number(event.target.value))}/></div><div className="md:col-span-2"><Label>Adres Bilgisi</Label><Input disabled={readOnly} value={address} onChange={event=>setAddress(event.target.value)}/></div><div><Label>Durum</Label><Select disabled={readOnly} value={status} onValueChange={value=>setStatus(value as HpSheetStatus)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{statuses.map(item=><SelectItem key={item.value} value={item.value}>{item.label}</SelectItem>)}</SelectContent></Select></div>{status==="in_progress"&&<div><Label>Mevcut Ekip Başı / Ekibe Aktar *</Label><Select disabled={readOnly} value={leaderId} onValueChange={setLeaderId}><SelectTrigger><SelectValue placeholder="Ekip başı seçin"/></SelectTrigger><SelectContent>{personnel.map(person=><SelectItem key={person.id} value={person.id}>{person.full_name}</SelectItem>)}</SelectContent></Select></div>}{status==="completed"&&<div><Label>Bitiren Ekip Başı *</Label><Select disabled={readOnly} value={finisherId} onValueChange={setFinisherId}><SelectTrigger><SelectValue placeholder="Ekip başı seçin"/></SelectTrigger><SelectContent>{personnel.map(person=><SelectItem key={person.id} value={person.id}>{person.full_name}</SelectItem>)}</SelectContent></Select></div>}<div className="md:col-span-2"><Label>Not</Label><Textarea disabled={readOnly} value={notes} onChange={event=>setNotes(event.target.value)} placeholder="Pafta ile ilgili gerekli bilgiler..."/></div></div>{!readOnly&&<Button className="mt-4" onClick={save} disabled={saving}>{saving?"Kaydediliyor...":"Paftayı Kaydet"}</Button>}</div></details>
}
