"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import type { HpSheetStatus, Project, ProjectSheet } from "@/types/project";
import type { Personnel } from "@/types/work-plan";
import { createClient } from "@/lib/supabase/client";
import { Button } from "@/components/ui/button";
import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from "@/components/ui/select";

const statuses:{value:HpSheetStatus;label:string;order:number}[]=[
 {value:"not_started",label:"Başlamadı",order:0},{value:"excavation_permit_waiting",label:"Kazı İzni Bekliyor",order:1},{value:"in_progress",label:"Devam Ediyor",order:2},{value:"completed",label:"Bitti",order:3},
];
export function HpFocusedSheetManager({project,sheets,personnel,readOnly}:{project:Project;sheets:ProjectSheet[];personnel:Personnel[];readOnly:boolean}){
 const router=useRouter(),[adding,setAdding]=useState(false);
 const sorted=[...sheets].sort((a,b)=>(statuses.find(s=>s.value===a.manual_status)?.order??0)-(statuses.find(s=>s.value===b.manual_status)?.order??0)||a.name.localeCompare(b.name,"tr"));
 async function addSheet(){const {data:{user}}=await createClient().auth.getUser();const {error}=await createClient().from("project_sheets").insert({project_id:project.id,name:`Pafta ${sheets.length+1}`,sheet_no:`Pafta ${sheets.length+1}`,manual_status:"not_started",tracks_cable:false,tracks_joint:false,tracks_obk:false,tracks_excavation:false,created_by:user?.id});if(error)return toast.error("Pafta eklenemedi");setAdding(false);router.refresh()}
 return <Card><CardHeader><CardTitle className="flex items-center justify-between gap-3 text-base"><span>HP Odaklı Paftalar</span><span className="text-blue-600">%{project.progress_percent??0}</span></CardTitle></CardHeader><CardContent className="space-y-4"><div className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full bg-blue-600 transition-all" style={{width:`${project.progress_percent??0}%`}}/></div>{!readOnly&&<div className="flex justify-end"><Button variant="outline" onClick={()=>setAdding(v=>!v)}>{adding?"Vazgeç":"Pafta Ekle"}</Button></div>}{adding&&<div className="rounded-xl border p-3"><p className="mb-2 text-sm text-muted-foreground">Yeni pafta oluşturulduktan sonra pafta numarası ve diğer alanları karttan düzenleyebilirsiniz.</p><Button onClick={addSheet}>Yeni Paftayı Oluştur</Button></div>}{sorted.map(sheet=><HpSheetCard key={sheet.id} sheet={sheet} personnel={personnel} readOnly={readOnly} onSaved={()=>router.refresh()}/>)}</CardContent></Card>
}
function HpSheetCard({sheet,personnel,readOnly,onSaved}:{sheet:ProjectSheet;personnel:Personnel[];readOnly:boolean;onSaved:()=>void}){
 const [sheetNo,setSheetNo]=useState(sheet.sheet_no??sheet.name),[address,setAddress]=useState(sheet.address??""),[hp,setHp]=useState(sheet.hp_count??0),[notes,setNotes]=useState(sheet.notes??""),[status,setStatus]=useState<HpSheetStatus>(sheet.manual_status),[finisherId,setFinisherId]=useState(sheet.completed_by_personnel_id??""),[saving,setSaving]=useState(false);
 async function save(){if(!sheetNo.trim())return toast.error("Pafta No zorunlu");if(status==="completed"&&!finisherId)return toast.error("Paftayı bitiren ekip başını seçin");const finisher=personnel.find(person=>person.id===finisherId);setSaving(true);const {error}=await createClient().from("project_sheets").update({name:sheetNo.trim(),sheet_no:sheetNo.trim(),address:address.trim()||null,hp_count:Number(hp)||0,notes:notes.trim()||null,manual_status:status,is_completed:status==="completed",completed_at:status==="completed"?new Date().toISOString().slice(0,10):null,completed_by_personnel_id:status==="completed"?finisherId:null,completed_by_name:status==="completed"?finisher?.full_name:null}).eq("id",sheet.id);setSaving(false);if(error)return toast.error("Pafta kaydedilemedi");toast.success("Pafta güncellendi");onSaved()}
 const statusLabel=statuses.find(s=>s.value===sheet.manual_status)?.label;
 return <div className={`space-y-3 rounded-xl border p-4 ${sheet.manual_status==="completed"?"border-blue-400 bg-blue-50 dark:border-blue-700 dark:bg-blue-950/40":""}`}><div className="flex items-center justify-between"><strong>{sheet.sheet_no||sheet.name}</strong><span className="rounded-full bg-muted px-3 py-1 text-xs">{statusLabel}</span></div><div className="grid gap-3 md:grid-cols-2"><div><Label>Pafta No</Label><Input disabled={readOnly} value={sheetNo} onChange={e=>setSheetNo(e.target.value)}/></div><div><Label>HP Adedi</Label><Input disabled={readOnly} type="number" min="0" value={hp} onChange={e=>setHp(Number(e.target.value))}/></div><div className="md:col-span-2"><Label>Adres Bilgisi</Label><Input disabled={readOnly} value={address} onChange={e=>setAddress(e.target.value)}/></div><div><Label>Durum</Label><Select disabled={readOnly} value={status} onValueChange={v=>setStatus(v as HpSheetStatus)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{statuses.map(s=><SelectItem key={s.value} value={s.value}>{s.label}</SelectItem>)}</SelectContent></Select></div>{status==="completed"&&<div><Label>Bitiren Ekip Başı *</Label><Select disabled={readOnly} value={finisherId} onValueChange={setFinisherId}><SelectTrigger><SelectValue placeholder="Ekip başı seçin"/></SelectTrigger><SelectContent>{personnel.map(person=><SelectItem key={person.id} value={person.id}>{person.full_name}</SelectItem>)}</SelectContent></Select></div>}<div className="md:col-span-2"><Label>Not</Label><Textarea disabled={readOnly} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Pafta ile ilgili gerekli bilgiler..."/></div></div>{!readOnly&&<Button onClick={save} disabled={saving}>{saving?"Kaydediliyor...":"Paftayı Kaydet"}</Button>}</div>
}
