"use client";
import { useMemo, useState } from "react";
import { Download, Hammer, Loader2, Plus, Settings2, Trash2 } from "lucide-react";
import { toast } from "sonner";
import type { DailyWorkPlanWithTeams, WorkPlanTeamSnapshot } from "@/types/work-plan";
import type { Project } from "@/types/project";
import type { ProductionDefinition, ProductionEntry, ProductionSaveJob } from "@/types/production";
import { createClient } from "@/lib/supabase/client";
import { formatDate } from "@/lib/utils";
import { downloadProductionWord } from "@/lib/production-word";
import { WorkPlanRepository } from "@/modules/work-plans/work-plan-repository";
import { ProductionRepository } from "@/modules/productions/production-repository";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

type FormItem = { definition_id: string; quantity: string };
type FormJob = { project_id: string; project_name: string; project_code: string; source: "work_plan" | "manual"; items: FormItem[] };
type Leader = { id: string; name: string; team: WorkPlanTeamSnapshot };

export function ProductionsManager({ initialDate, initialPlan, initialDefinitions, initialEntries, projects, readOnly }: {
  initialDate: string; initialPlan: DailyWorkPlanWithTeams | null; initialDefinitions: ProductionDefinition[]; initialEntries: ProductionEntry[]; projects: Project[]; readOnly: boolean;
}) {
  const [date, setDate] = useState(initialDate); const [plan, setPlan] = useState(initialPlan);
  const [dailyEntries, setDailyEntries] = useState(initialEntries.filter((e) => e.work_date === initialDate));
  const [reportEntries, setReportEntries] = useState(initialEntries); const [definitions, setDefinitions] = useState(initialDefinitions);
  const [editor, setEditor] = useState<{ leader: Leader; entry: ProductionEntry | null } | null>(null);
  const [jobs, setJobs] = useState<FormJob[]>([]); const [loading, setLoading] = useState(false);
  const [definitionOpen, setDefinitionOpen] = useState(false); const [newDefinition, setNewDefinition] = useState({ name: "", unit: "ADET" });
  const month = initialDate.slice(0,7); const [from, setFrom] = useState(`${month}-01`); const [to, setTo] = useState(`${month}-${String(new Date(Number(month.slice(0,4)),Number(month.slice(5,7)),0).getDate()).padStart(2,"0")}`);
  const [leaderFilter, setLeaderFilter] = useState("all"); const [projectFilter, setProjectFilter] = useState("all");

  const leaders = useMemo(() => {
    const map = new Map<string, Leader>();
    for (const team of plan?.teams ?? []) {
      const chiefMember = team.members.find((member) => member.is_chief);
      const id = team.chief_personnel_id || chiefMember?.personnel_id;
      if (id && !map.has(id)) map.set(id, { id, name: chiefMember?.full_name || team.chief_name, team });
    }
    return [...map.values()];
  }, [plan]);

  async function changeDate(nextDate: string) {
    setDate(nextDate); setLoading(true);
    try { const supabase=createClient(); const [nextPlan, entries]=await Promise.all([new WorkPlanRepository(supabase).getByDate(nextDate),new ProductionRepository(supabase).listEntries(nextDate,nextDate)]); setPlan(nextPlan); setDailyEntries(entries); }
    catch(error){ console.error(error); toast.error("Tarih bilgileri yüklenemedi"); } finally { setLoading(false); }
  }
  function openEditor(leader: Leader) {
    const entry=dailyEntries.find((e)=>e.team_leader_personnel_id===leader.id) ?? null;
    setEditor({leader,entry});
    setJobs(entry ? entry.jobs.map((job)=>({ project_id:job.project_id||"",project_name:job.project_name_snapshot,project_code:job.project_code_snapshot||"",source:job.source,items:job.items.map((item)=>({definition_id:item.production_item_definition_id||"",quantity:String(item.quantity)})) })) : [{ project_id:"",project_name:leader.team.project_name,project_code:leader.team.project_code,source:"work_plan",items:[] }]);
  }
  function addJob(){ setJobs((current)=>[...current,{project_id:"",project_name:"",project_code:"",source:"manual",items:[]}]); }
  function addItem(jobIndex:number){ const first=definitions.find((d)=>d.is_active); if(!first){toast.error("Önce aktif imalat kalemi tanımlayın");return;} setJobs((current)=>current.map((job,index)=>index===jobIndex?{...job,items:[...job.items,{definition_id:first.id,quantity:""}]}:job)); }
  function updateJob(index:number, patch:Partial<FormJob>){setJobs((current)=>current.map((job,i)=>i===index?{...job,...patch}:job));}
  function updateItem(jobIndex:number,itemIndex:number,patch:Partial<FormItem>){
    setJobs((current)=>current.map((job,j)=>j===jobIndex
      ? {...job,items:job.items.map((item,i)=>i===itemIndex?{...item,...patch}:item)}
      : job));
  }
  async function saveEntry(){ if(!editor||!plan)return; if(jobs.some((job)=>job.project_name.trim().length<2||job.items.length===0||job.items.some((item)=>!item.definition_id||Number(item.quantity)<=0))){toast.error("Her işte proje ve en az bir geçerli imalat satırı olmalı");return;} setLoading(true); try{const repo=new ProductionRepository(createClient()); const payload:ProductionSaveJob[]=jobs.map((job,j)=>({...job,project_id:job.project_id||null,sort_order:j,items:job.items.map((item,i)=>({definition_id:item.definition_id,quantity:Number(item.quantity),sort_order:i}))})); await repo.saveEntry({entry_id:editor.entry?.id,work_date:date,leader_id:editor.leader.id,leader_name:editor.leader.name,work_plan_id:plan.id,jobs:payload}); const entries=await repo.listEntries(date,date);setDailyEntries(entries);setEditor(null);toast.success("İmalat kaydedildi");}catch(error){console.error(error);toast.error("İmalat kaydedilemedi",{description:(error as Error).message});}finally{setLoading(false);}}
  async function deleteEntry(entry:ProductionEntry){if(!confirm("Bu günlük imalat kaydı silinsin mi?"))return;setLoading(true);try{const repo=new ProductionRepository(createClient());await repo.deleteEntry(entry.id);setDailyEntries((x)=>x.filter((e)=>e.id!==entry.id));toast.success("İmalat silindi");}catch(error){toast.error("Kayıt silinemedi",{description:(error as Error).message});}finally{setLoading(false);}}
  async function saveDefinition(){if(newDefinition.name.trim().length<2||!newDefinition.unit.trim()){toast.error("Ad ve birim zorunlu");return;}try{const repo=new ProductionRepository(createClient());const saved=await repo.saveDefinition({...newDefinition,is_active:true});setDefinitions((x)=>[...x,saved].sort((a,b)=>a.name.localeCompare(b.name,"tr")));setNewDefinition({name:"",unit:"ADET"});toast.success("İmalat kalemi eklendi");}catch(error){toast.error("Kalem eklenemedi",{description:(error as Error).message});}}
  async function toggleDefinition(def:ProductionDefinition){try{const saved=await new ProductionRepository(createClient()).saveDefinition({...def,is_active:!def.is_active});setDefinitions((x)=>x.map((d)=>d.id===saved.id?saved:d));}catch(error){toast.error("Kalem güncellenemedi",{description:(error as Error).message});}}
  async function loadReport(nextFrom=from,nextTo=to){setLoading(true);try{setReportEntries(await new ProductionRepository(createClient()).listEntries(nextFrom,nextTo));}catch{toast.error("Rapor yüklenemedi");}finally{setLoading(false);}}
  function preset(kind:"today"|"month"|"previous"){const now=new Date();let start:string,end:string;if(kind==="today"){start=end=new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Istanbul"}).format(now);}else{const d=kind==="month"?now:new Date(now.getFullYear(),now.getMonth()-1,1);const m=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`;start=`${m}-01`;end=`${m}-${String(new Date(d.getFullYear(),d.getMonth()+1,0).getDate()).padStart(2,"0")}`;}setFrom(start);setTo(end);void loadReport(start,end);}
  const filteredReport=reportEntries
    .filter((entry)=>leaderFilter==="all"||entry.team_leader_personnel_id===leaderFilter)
    .map((entry)=>projectFilter==="all"?entry:{...entry,jobs:entry.jobs.filter((job)=>job.project_name_snapshot===projectFilter)})
    .filter((entry)=>entry.jobs.length>0);
  const reportLeaders=[...new Map(reportEntries.map((e)=>[e.team_leader_personnel_id,e.team_leader_name_snapshot])).entries()];
  const reportProjects=[...new Set(reportEntries.flatMap((e)=>e.jobs.map((j)=>j.project_name_snapshot)))].sort();

  return <div className="space-y-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-3xl font-semibold">İmalatlar</h1><p className="mt-1 text-sm text-muted-foreground">Günlük ekip başı imalat kayıtları</p></div><div className="flex gap-2">{!readOnly&&<Button variant="outline" onClick={()=>setDefinitionOpen(true)}><Settings2 className="h-4 w-4"/>İmalat Kalemleri</Button>}<Button variant="outline" onClick={()=>downloadProductionWord(filteredReport,from,to,leaderFilter==="all"?undefined:reportLeaders.find(([id])=>id===leaderFilter)?.[1])}><Download className="h-4 w-4"/>Word</Button></div></div>
    <Card><CardHeader><CardTitle className="text-base">Günlük İmalat Girişi</CardTitle></CardHeader><CardContent className="space-y-4"><div className="max-w-xs space-y-2"><Label>Tarih</Label><Input type="date" value={date} onChange={(e)=>void changeDate(e.target.value)}/></div>{loading&&<Loader2 className="h-5 w-5 animate-spin"/>}{!plan&&!loading&&<p className="rounded-xl border p-4 text-sm text-muted-foreground">Bu tarihte iş planı bulunmuyor.</p>}<div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{leaders.map((leader)=>{const entry=dailyEntries.find((e)=>e.team_leader_personnel_id===leader.id);return <div key={leader.id} className="rounded-xl border p-4"><div className="flex justify-between gap-2"><div><p className="font-semibold">{leader.name}</p><p className="text-sm">{leader.team.project_name}</p><p className="text-xs text-muted-foreground">Proje ID: {leader.team.project_code||"—"}</p></div>{entry&&<Hammer className="h-5 w-5 text-emerald-600"/>}</div>{entry&&<div className="mt-3 space-y-2">{entry.jobs.map((job)=><div key={job.id} className="rounded-lg bg-muted p-2 text-xs"><strong>{job.project_name_snapshot}</strong>{job.items.map((item)=><p key={item.id}>{item.item_name_snapshot} · {Number(item.quantity).toLocaleString("tr-TR")} {item.unit_snapshot}</p>)}</div>)}</div>}<div className="mt-3 flex gap-2">{!readOnly&&<Button size="sm" className="flex-1" onClick={()=>openEditor(leader)}>{entry?"Düzenle":"İmalat Gir"}</Button>}{entry&&!readOnly&&<Button size="icon" variant="outline" onClick={()=>void deleteEntry(entry)}><Trash2 className="h-4 w-4"/></Button>}</div></div>})}</div></CardContent></Card>
    <Card><CardHeader><CardTitle className="text-base">İmalat Raporu</CardTitle></CardHeader><CardContent className="space-y-4"><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={()=>preset("today")}>Bugün</Button><Button size="sm" variant="outline" onClick={()=>preset("month")}>Bu Ay</Button><Button size="sm" variant="outline" onClick={()=>preset("previous")}>Geçen Ay</Button></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Field label="Başlangıç"><Input type="date" value={from} onChange={(e)=>setFrom(e.target.value)}/></Field><Field label="Bitiş"><Input type="date" value={to} onChange={(e)=>setTo(e.target.value)}/></Field><Field label="Ekip Başı"><Select value={leaderFilter} onValueChange={setLeaderFilter}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Tüm Ekip Başları</SelectItem>{reportLeaders.map(([id,name])=><SelectItem key={id} value={id}>{name}</SelectItem>)}</SelectContent></Select></Field><Field label="Proje"><Select value={projectFilter} onValueChange={setProjectFilter}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Tümü</SelectItem>{reportProjects.map((name)=><SelectItem key={name} value={name}>{name}</SelectItem>)}</SelectContent></Select></Field></div><Button onClick={()=>void loadReport()}>Raporu Getir</Button><div className="space-y-4">{filteredReport.map((entry)=><div key={entry.id} className="rounded-xl border p-4"><p className="font-bold">{entry.team_leader_name_snapshot}</p><p className="text-sm text-muted-foreground">{formatDate(entry.work_date)}</p>{entry.jobs.map((job)=><div key={job.id} className="mt-3 border-l-2 pl-3"><p className="font-medium">{job.project_name_snapshot} {job.project_code_snapshot&&`/ ${job.project_code_snapshot}`}</p>{job.items.map((item)=><p key={item.id} className="text-sm">{item.item_name_snapshot} — {Number(item.quantity).toLocaleString("tr-TR")} {item.unit_snapshot}</p>)}</div>)}</div>)}{!filteredReport.length&&<p className="text-sm text-muted-foreground">Filtreye uygun kayıt yok.</p>}</div></CardContent></Card>
    <Dialog open={Boolean(editor)} onOpenChange={(open)=>!open&&setEditor(null)}><DialogContent className="max-h-[92vh] overflow-y-auto sm:max-w-3xl"><DialogHeader><DialogTitle>{editor?.leader.name} · {formatDate(date)}</DialogTitle></DialogHeader><div className="space-y-4">{jobs.map((job,j)=><div key={j} className="rounded-xl border p-3"><div className="mb-3 flex justify-between"><strong>İş {j+1}</strong>{job.source==="manual"&&<Button size="icon" variant="ghost" onClick={()=>setJobs((x)=>x.filter((_,i)=>i!==j))}><Trash2 className="h-4 w-4"/></Button>}</div>{job.source==="manual"&&<Field label="Projelerden Seç"><Select value={job.project_id||"manual"} onValueChange={(value)=>{if(value==="manual")updateJob(j,{project_id:""});else{const p=projects.find((x)=>x.id===value);if(p)updateJob(j,{project_id:p.id,project_name:p.name,project_code:p.project_code});}}}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="manual">Manuel / Geçici Proje</SelectItem>{projects.map((p)=><SelectItem key={p.id} value={p.id}>{p.name} · {p.project_code}</SelectItem>)}</SelectContent></Select></Field>}<div className="mt-3 grid gap-3 sm:grid-cols-2"><Field label="Proje Adı"><Input value={job.project_name} readOnly={job.source==="work_plan"} onChange={(e)=>updateJob(j,{project_name:e.target.value})}/></Field><Field label="Proje ID"><Input value={job.project_code} readOnly={job.source==="work_plan"} onChange={(e)=>updateJob(j,{project_code:e.target.value})}/></Field></div><div className="mt-3 space-y-2">{job.items.map((item,i)=>{const def=definitions.find((d)=>d.id===item.definition_id);return <div key={i} className="grid grid-cols-[1fr_100px_auto] items-end gap-2"><Field label="İmalat Kalemi"><Select value={item.definition_id} onValueChange={(value)=>updateItem(j,i,{definition_id:value})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{definitions.filter((d)=>d.is_active||d.id===item.definition_id).map((d)=><SelectItem key={d.id} value={d.id}>{d.name}</SelectItem>)}</SelectContent></Select></Field><Field label={`Miktar (${def?.unit||""})`}><Input type="number" min="0.001" step="0.001" value={item.quantity} onChange={(e)=>updateItem(j,i,{quantity:e.target.value})}/></Field><Button size="icon" variant="outline" onClick={()=>setJobs((x)=>x.map((jj,ji)=>ji===j?{...jj,items:jj.items.filter((_,ii)=>ii!==i)}:jj))}><Trash2 className="h-4 w-4"/></Button></div>})}<Button variant="outline" className="w-full" onClick={()=>addItem(j)}><Plus className="h-4 w-4"/>İmalat Ekle</Button></div></div>)}<Button variant="outline" className="w-full" onClick={addJob}><Plus className="h-4 w-4"/>İş Ekle</Button><Button className="w-full" disabled={loading} onClick={()=>void saveEntry()}>{loading&&<Loader2 className="h-4 w-4 animate-spin"/>}Kaydet</Button></div></DialogContent></Dialog>
    <Dialog open={definitionOpen} onOpenChange={setDefinitionOpen}><DialogContent><DialogHeader><DialogTitle>İmalat Kalemleri</DialogTitle></DialogHeader><div className="space-y-4"><div className="grid grid-cols-[1fr_100px] gap-2"><Field label="Ad"><Input value={newDefinition.name} onChange={(e)=>setNewDefinition((x)=>({...x,name:e.target.value}))}/></Field><Field label="Birim"><Input value={newDefinition.unit} onChange={(e)=>setNewDefinition((x)=>({...x,unit:e.target.value}))}/></Field></div><Button className="w-full" onClick={()=>void saveDefinition()}><Plus className="h-4 w-4"/>Kalem Ekle</Button><div className="space-y-2">{definitions.map((def)=><button key={def.id} onClick={()=>void toggleDefinition(def)} className="flex w-full justify-between rounded-lg border p-3 text-left"><span>{def.name} · {def.unit}</span><span className={def.is_active?"text-emerald-600":"text-muted-foreground"}>{def.is_active?"Aktif":"Pasif"}</span></button>)}</div></div></DialogContent></Dialog>
  </div>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-2"><Label>{label}</Label>{children}</div>;}
