"use client";

import { useMemo, useState } from "react";
import { ArrowDownToLine, ArrowUpFromLine, Loader2, Plus, Send, Trash2 } from "lucide-react";
import { toast } from "sonner";
import type { InventoryLocation, InventoryMaterial, InventoryReceipt, InventoryShipment, InventoryStockCategory, InventoryUnit } from "@/types/inventory";
import type { Personnel } from "@/types/work-plan";
import { INVENTORY_STOCK_CATEGORIES, INVENTORY_UNITS, formatInventoryQuantity, getInventoryStockCategoryLabel } from "@/lib/constants/inventory";
import { createClient } from "@/lib/supabase/client";
import { InventoryRepository } from "@/modules/inventory/inventory-repository";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";

type StockView = "all" | "center" | "biga";
type Line = { material_id: string; quantity: string };
const today = () => new Date().toLocaleDateString("en-CA");

export function InventoryManager({ initialMaterials, initialShipments, initialReceipts, personnel, readOnly = false }: {
  initialMaterials: InventoryMaterial[]; initialMovements: unknown[]; initialShipments: InventoryShipment[]; initialReceipts: InventoryReceipt[]; personnel: Personnel[]; readOnly?: boolean;
}) {
  const [materials, setMaterials] = useState(initialMaterials);
  const [shipments, setShipments] = useState(initialShipments);
  const [receipts, setReceipts] = useState(initialReceipts);
  const [stockView, setStockView] = useState<StockView>("all");
  const [category, setCategory] = useState<InventoryStockCategory | "all">("all");
  const [search, setSearch] = useState("");
  const [catalogOpen, setCatalogOpen] = useState(false);
  const [receiptOpen, setReceiptOpen] = useState(false);
  const [shipmentOpen, setShipmentOpen] = useState(false);
  const [movement, setMovement] = useState<{ material: InventoryMaterial; type: "in" | "out" } | null>(null);
  const [deleteMaterial, setDeleteMaterial] = useState<InventoryMaterial | null>(null);
  const [loading, setLoading] = useState(false);

  const filtered = useMemo(() => {
    const query = search.trim().toLocaleLowerCase("tr-TR");
    return materials.filter((item) => {
      if (category !== "all" && item.stock_category !== category) return false;
      if (stockView === "center" && Number(item.stock_quantity) <= 0) return false;
      if (stockView === "biga" && Number(item.biga_stock_quantity) <= 0) return false;
      return !query || [item.material_name, item.material_code ?? "", item.material_type ?? "", item.size ?? ""].some((value) => value.toLocaleLowerCase("tr-TR").includes(query));
    }).sort((a, b) => {
      const order = ["fiber_cable", "copper_network", "fiber_accessory"];
      const categoryOrder = order.indexOf(a.stock_category ?? "") - order.indexOf(b.stock_category ?? "");
      return categoryOrder || a.material_name.localeCompare(b.material_name, "tr");
    });
  }, [materials, category, stockView, search]);

  async function reload(repository: InventoryRepository) {
    const [nextMaterials, nextShipments, nextReceipts] = await Promise.all([repository.listMaterials("stock"), repository.listShipments(), repository.listReceipts()]);
    setMaterials(nextMaterials); setShipments(nextShipments); setReceipts(nextReceipts);
  }
  async function run(action: (repository: InventoryRepository) => Promise<unknown>, success: string) {
    setLoading(true); try { const repository = new InventoryRepository(createClient()); await action(repository); await reload(repository); toast.success(success); return true; }
    catch (error) { toast.error("İşlem tamamlanamadı", { description: (error as Error)?.message }); return false; }
    finally { setLoading(false); }
  }

  return <div className="space-y-6">
    <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><h1 className="text-3xl font-semibold">Malzeme Stok</h1><p className="mt-1 text-sm text-muted-foreground">Malzeme kataloğu, irsaliye girişleri ve şube stokları</p></div>{!readOnly && <div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => setShipmentOpen(true)}><Send />Biga Sevkiyatı</Button><Button variant="outline" onClick={() => setReceiptOpen(true)}><ArrowDownToLine />İrsaliye ile Stok Girişi</Button><Button onClick={() => setCatalogOpen(true)}><Plus />Yeni Malzeme</Button></div>}</div>

    <section className="space-y-4">
      <div className="flex flex-wrap gap-3" aria-label="Stok konumu">{([{ value: "all", label: "Tüm Malzemeler", color: "bg-zinc-700" }, { value: "center", label: "Merkez Şantiye", color: "bg-emerald-600" }, { value: "biga", label: "Biga Şantiye", color: "bg-blue-600" }] as const).map((item) => <button key={item.value} type="button" onClick={() => setStockView(item.value)} className={`flex h-16 w-16 items-center justify-center rounded-full px-2 text-center text-[11px] font-semibold leading-tight text-white shadow-sm transition-transform hover:-translate-y-0.5 ${item.color} ${stockView === item.value ? "ring-2 ring-ring ring-offset-2" : "opacity-75"}`}>{item.label}</button>)}</div>
      <div className="flex flex-wrap gap-3" aria-label="Malzeme kategorileri">{INVENTORY_STOCK_CATEGORIES.map((item, index) => <button key={item.value} type="button" title={item.label} onClick={() => setCategory(item.value)} className={`flex h-14 w-14 items-center justify-center rounded-full px-1 text-center text-[10px] font-bold leading-tight text-white shadow-sm transition-transform hover:-translate-y-0.5 ${index === 0 ? "bg-cyan-700" : index === 1 ? "bg-amber-700" : "bg-violet-700"} ${category === item.value ? "ring-2 ring-ring ring-offset-2" : "opacity-75"}`}>{item.label.replace(" Malzeme", "")}</button>)}</div>
      <div className="grid gap-3 sm:grid-cols-[240px_1fr]"><Select value={category} onValueChange={(value: InventoryStockCategory | "all") => setCategory(value)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">Tüm Kategoriler</SelectItem>{INVENTORY_STOCK_CATEGORIES.map((item) => <SelectItem key={item.value} value={item.value}>{item.label}</SelectItem>)}</SelectContent></Select><Input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Malzeme adı, türü, ebatı veya ID ara..." /></div>

      <div className="overflow-x-auto border-y"><table className="w-full min-w-[1000px] text-left text-sm"><thead><tr className="border-b bg-muted/50 text-muted-foreground"><th className="px-3 py-3">Kategori</th><th className="px-3 py-3">Malzeme Adı</th><th className="px-3 py-3">Tür</th><th className="px-3 py-3">Ebat</th><th className="px-3 py-3">ID</th><th className="px-3 py-3">Merkez</th><th className="px-3 py-3">Biga</th>{!readOnly && <th className="px-3 py-3">İşlemler</th>}</tr></thead><tbody>{filtered.map((material) => <tr key={material.id} className="border-b last:border-0"><td className="px-3 py-3"><Badge className="bg-secondary text-secondary-foreground">{getInventoryStockCategoryLabel(material.stock_category)}</Badge></td><td className="px-3 py-3 font-semibold">{material.material_name}</td><td className="px-3 py-3">{material.material_type || "—"}</td><td className="px-3 py-3">{material.size || "—"}</td><td className="px-3 py-3">{material.material_code || "—"}</td><td className="px-3 py-3">{formatInventoryQuantity(material.stock_quantity, material.unit)}</td><td className="px-3 py-3">{formatInventoryQuantity(material.biga_stock_quantity, material.unit)}</td>{!readOnly && <td className="px-3 py-3"><div className="flex gap-1"><Button title="Stoktan düş" variant="ghost" size="icon" disabled={Number(material.stock_quantity) + Number(material.biga_stock_quantity) <= 0} onClick={() => setMovement({ material, type: "out" })}><ArrowUpFromLine /></Button><Button title="Malzemeyi tamamen sil" variant="ghost" size="icon" className="text-destructive" onClick={() => setDeleteMaterial(material)}><Trash2 /></Button></div></td>}</tr>)}</tbody></table></div>
      {!filtered.length && <p className="py-10 text-center text-sm text-muted-foreground">Bu filtrede malzeme bulunamadı.</p>}
    </section>

    <ReceiptHistory receipts={receipts} />
    <ShipmentHistory shipments={shipments} />
    <CatalogDialog open={catalogOpen} setOpen={setCatalogOpen} loading={loading} onSave={async (payload) => { const ok = await run((repository) => repository.createCatalogMaterial(payload), "Malzeme kataloğa eklendi"); if (ok) setCatalogOpen(false); }} />
    <ReceiptDialog open={receiptOpen} setOpen={setReceiptOpen} materials={materials} loading={loading} onSave={async (payload) => { const ok = await run((repository) => repository.createReceipt(payload), "İrsaliye stoğa işlendi"); if (ok) setReceiptOpen(false); }} />
    <ShipmentDialog open={shipmentOpen} setOpen={setShipmentOpen} materials={materials} loading={loading} onSave={async (payload) => { const ok = await run((repository) => repository.createBigaShipment(payload), "Biga sevkiyatı kaydedildi"); if (ok) setShipmentOpen(false); }} />
    <MovementDialog state={movement} setState={setMovement} personnel={personnel} loading={loading} onSave={async (payload) => { const ok = await run((repository) => repository.recordMovement(payload), payload.movement_type === "out" ? "Malzeme stoktan düşüldü" : "Merkez stokuna eklendi"); if (ok) setMovement(null); }} />
    <ConfirmDialog open={Boolean(deleteMaterial)} title="Malzemeyi Tamamen Sil" description="Bu malzemenin Merkez ve Biga stoklarıyla birlikte tüm giriş, düşüm ve sevkiyat test kayıtları kalıcı olarak silinecek." setOpen={(open) => !open && setDeleteMaterial(null)} loading={loading} onConfirm={async () => { if (!deleteMaterial) return; const ok = await run((repository) => repository.deleteMaterial(deleteMaterial.id), "Malzeme ve tüm geçmişi silindi"); if (ok) setDeleteMaterial(null); }} />
  </div>;
}

function CatalogDialog({ open, setOpen, loading, onSave }: { open: boolean; setOpen: (open: boolean) => void; loading: boolean; onSave: (payload: { material_name: string; material_code?: string; stock_category: InventoryStockCategory; material_type?: string; size?: string; unit: InventoryUnit; notes?: string }) => Promise<void> }) {
  const [data, setData] = useState({ material_name: "", material_code: "", stock_category: "fiber_cable" as InventoryStockCategory, material_type: "", size: "", unit: "piece" as InventoryUnit, notes: "" });
  return <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>Yeni Malzeme Kaydı</DialogTitle></DialogHeader><form className="grid gap-4 sm:grid-cols-2" onSubmit={(event) => { event.preventDefault(); if (data.material_name.trim().length < 2) return toast.error("Malzeme adı zorunlu"); void onSave(data); }}><Field label="Kategori"><Select value={data.stock_category} onValueChange={(value: InventoryStockCategory) => setData({ ...data, stock_category: value })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{INVENTORY_STOCK_CATEGORIES.map((item) => <SelectItem key={item.value} value={item.value}>{item.label}</SelectItem>)}</SelectContent></Select></Field><Field label="Malzeme Adı"><Input value={data.material_name} onChange={(e) => setData({ ...data, material_name: e.target.value })} /></Field><Field label="Tür"><Input value={data.material_type} onChange={(e) => setData({ ...data, material_type: e.target.value })} /></Field><Field label="Ebat"><Input value={data.size} onChange={(e) => setData({ ...data, size: e.target.value })} /></Field><Field label="Malzeme ID (Zorunlu Değil)"><Input value={data.material_code} onChange={(e) => setData({ ...data, material_code: e.target.value })} /></Field><Field label="Birim"><Select value={data.unit} onValueChange={(value: InventoryUnit) => setData({ ...data, unit: value })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{INVENTORY_UNITS.map((item) => <SelectItem key={item.value} value={item.value}>{item.label}</SelectItem>)}</SelectContent></Select></Field><div className="sm:col-span-2"><Field label="Not"><Textarea value={data.notes} onChange={(e) => setData({ ...data, notes: e.target.value })} /></Field></div><Button className="sm:col-span-2" disabled={loading}>{loading && <Loader2 className="animate-spin" />}Malzemeyi Kaydet</Button></form></DialogContent></Dialog>;
}

function ReceiptDialog({ open, setOpen, materials, loading, onSave }: { open: boolean; setOpen: (open: boolean) => void; materials: InventoryMaterial[]; loading: boolean; onSave: (payload: { receipt_date: string; received_by: string; dispatch_number: string; notes?: string; items: { material_id: string; quantity: number }[] }) => Promise<void> }) {
  const [data, setData] = useState({ receipt_date: today(), received_by: "", dispatch_number: "", notes: "" }); const [lines, setLines] = useState<Line[]>([{ material_id: "", quantity: "1" }]);
  return <DocumentDialog open={open} setOpen={setOpen} title="İrsaliye ile Stok Girişi" loading={loading} materials={materials} lines={lines} setLines={setLines} submitLabel="Stoğa Al" fields={<><Field label="Teslim Tarihi"><Input type="date" value={data.receipt_date} onChange={(e) => setData({ ...data, receipt_date: e.target.value })} /></Field><Field label="İrsaliye No"><Input value={data.dispatch_number} onChange={(e) => setData({ ...data, dispatch_number: e.target.value })} /></Field><Field label="Teslim Alan"><Input value={data.received_by} onChange={(e) => setData({ ...data, received_by: e.target.value })} /></Field><Field label="Not"><Input value={data.notes} onChange={(e) => setData({ ...data, notes: e.target.value })} /></Field></>} onSubmit={() => onSave({ ...data, items: normalizeLines(lines) })} />;
}

function ShipmentDialog({ open, setOpen, materials, loading, onSave }: { open: boolean; setOpen: (open: boolean) => void; materials: InventoryMaterial[]; loading: boolean; onSave: (payload: { shipment_date: string; delivered_by: string; received_by: string; vehicle_plate: string; notes?: string; items: { material_id: string; quantity: number }[] }) => Promise<void> }) {
  const [data, setData] = useState({ shipment_date: today(), delivered_by: "", received_by: "", vehicle_plate: "", notes: "" }); const [lines, setLines] = useState<Line[]>([{ material_id: "", quantity: "1" }]);
  return <DocumentDialog open={open} setOpen={setOpen} title="AZG BİGA ŞUBE Sevkiyatı" loading={loading} materials={materials.filter((item) => Number(item.stock_quantity) > 0)} lines={lines} setLines={setLines} submitLabel="Sevkiyatı Kaydet" fields={<><Field label="Tarih"><Input type="date" value={data.shipment_date} onChange={(e) => setData({ ...data, shipment_date: e.target.value })} /></Field><Field label="Araç / Plaka"><Input value={data.vehicle_plate} onChange={(e) => setData({ ...data, vehicle_plate: e.target.value })} /></Field><Field label="Teslim Eden"><Input value={data.delivered_by} onChange={(e) => setData({ ...data, delivered_by: e.target.value })} /></Field><Field label="Teslim Alan"><Input value={data.received_by} onChange={(e) => setData({ ...data, received_by: e.target.value })} /></Field></>} onSubmit={() => onSave({ ...data, items: normalizeLines(lines) })} />;
}

function DocumentDialog({ open, setOpen, title, fields, materials, lines, setLines, loading, submitLabel, onSubmit }: { open: boolean; setOpen: (open: boolean) => void; title: string; fields: React.ReactNode; materials: InventoryMaterial[]; lines: Line[]; setLines: React.Dispatch<React.SetStateAction<Line[]>>; loading: boolean; submitLabel: string; onSubmit: () => Promise<void> }) {
  return <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-h-[90vh] max-w-2xl overflow-y-auto"><DialogHeader><DialogTitle>{title}</DialogTitle></DialogHeader><form className="space-y-4" onSubmit={(e) => { e.preventDefault(); if (!normalizeLines(lines).length) return toast.error("En az bir malzeme ekleyin"); void onSubmit(); }}><div className="grid gap-4 sm:grid-cols-2">{fields}</div><div className="space-y-2"><div className="flex items-center justify-between"><Label>Malzeme Listesi</Label><Button type="button" size="sm" variant="outline" onClick={() => setLines((value) => [...value, { material_id: "", quantity: "1" }])}><Plus />Satır Ekle</Button></div>{lines.map((line, index) => <div key={index} className="grid grid-cols-[1fr_120px_40px] gap-2"><Select value={line.material_id} onValueChange={(value) => setLines((current) => current.map((item, i) => i === index ? { ...item, material_id: value } : item))}><SelectTrigger><SelectValue placeholder="Malzeme seçin" /></SelectTrigger><SelectContent>{materials.map((item) => <SelectItem key={item.id} value={item.id}>{getInventoryStockCategoryLabel(item.stock_category)} · {item.material_name}{item.size ? ` · ${item.size}` : ""}</SelectItem>)}</SelectContent></Select><Input type="number" min="0" step="0.001" value={line.quantity} onChange={(e) => setLines((current) => current.map((item, i) => i === index ? { ...item, quantity: e.target.value } : item))} /><Button type="button" title="Satırı sil" variant="ghost" size="icon" disabled={lines.length === 1} onClick={() => setLines((current) => current.filter((_, i) => i !== index))}><Trash2 /></Button></div>)}</div><Button className="w-full" disabled={loading}>{loading && <Loader2 className="animate-spin" />}{submitLabel}</Button></form></DialogContent></Dialog>;
}

function MovementDialog({ state, setState, personnel, loading, onSave }: { state: { material: InventoryMaterial; type: "in" | "out" } | null; setState: (value: null) => void; personnel: Personnel[]; loading: boolean; onSave: (payload: { material_id: string; movement_type: "in" | "out"; quantity: number; source_location: InventoryLocation; project_name?: string; project_code?: string; team_personnel_ids?: string[]; description?: string }) => Promise<void> }) {
  const [quantity, setQuantity] = useState("1"); const [source, setSource] = useState<InventoryLocation>("center"); const [project, setProject] = useState(""); const [projectCode, setProjectCode] = useState(""); const [personId, setPersonId] = useState("");
  return <Dialog open={Boolean(state)} onOpenChange={(open) => !open && setState(null)}><DialogContent><DialogHeader><DialogTitle>{state?.type === "out" ? "Stoktan Düş" : "Merkez Stokuna Ekle"}</DialogTitle></DialogHeader>{state && <form className="space-y-4" onSubmit={(e) => { e.preventDefault(); if (state.type === "out" && project.trim().length < 2) return toast.error("Proje adı zorunlu"); void onSave({ material_id: state.material.id, movement_type: state.type, quantity: Number(quantity), source_location: source, project_name: project, project_code: projectCode, team_personnel_ids: personId ? [personId] : [] }); }}><p className="font-semibold">{state.material.material_name}</p>{state.type === "out" && <Field label="Stok Konumu"><Select value={source} onValueChange={(value: InventoryLocation) => setSource(value)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="center">Merkez Şantiye</SelectItem><SelectItem value="biga">Biga Şantiye</SelectItem></SelectContent></Select></Field>}<Field label="Miktar"><Input type="number" min="0" step="0.001" value={quantity} onChange={(e) => setQuantity(e.target.value)} /></Field>{state.type === "out" && <><Field label="Proje Adı"><Input value={project} onChange={(e) => setProject(e.target.value)} /></Field><Field label="Proje ID (Zorunlu Değil)"><Input value={projectCode} onChange={(e) => setProjectCode(e.target.value)} /></Field><Field label="Ekip (Zorunlu Değil)"><Select value={personId || "none"} onValueChange={(value) => setPersonId(value === "none" ? "" : value)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="none">Ekip seçilmedi</SelectItem>{personnel.map((person) => <SelectItem key={person.id} value={person.id}>{person.full_name}</SelectItem>)}</SelectContent></Select></Field></>}<Button className="w-full" disabled={loading}>Kaydet</Button></form>}</DialogContent></Dialog>;
}

function ReceiptHistory({ receipts }: { receipts: InventoryReceipt[] }) { return <Card><CardHeader><CardTitle className="text-base">İrsaliye Girişleri</CardTitle></CardHeader><CardContent>{receipts.map((receipt) => <div key={receipt.id} className="grid gap-2 border-b py-3 text-sm md:grid-cols-[120px_150px_160px_1fr]"><span>{new Date(`${receipt.receipt_date}T00:00:00`).toLocaleDateString("tr-TR")}</span><strong>{receipt.dispatch_number}</strong><span>{receipt.received_by}</span><span>{receipt.items.map((item) => `${item.material?.material_name ?? "—"}: ${item.material ? formatInventoryQuantity(item.quantity, item.material.unit) : item.quantity}`).join(", ")}</span></div>)}{!receipts.length && <p className="py-6 text-center text-sm text-muted-foreground">Henüz irsaliye girişi yok.</p>}</CardContent></Card>; }
function ShipmentHistory({ shipments }: { shipments: InventoryShipment[] }) { return <Card><CardHeader><CardTitle className="text-base">Biga Sevkiyatları</CardTitle></CardHeader><CardContent>{shipments.map((shipment) => <div key={shipment.id} className="grid gap-2 border-b py-3 text-sm md:grid-cols-[120px_120px_140px_140px_1fr]"><span>{new Date(`${shipment.shipment_date}T00:00:00`).toLocaleDateString("tr-TR")}</span><strong>{shipment.vehicle_plate}</strong><span>{shipment.delivered_by}</span><span>{shipment.received_by}</span><span>{shipment.items.map((item) => `${item.material?.material_name ?? "—"}: ${item.material ? formatInventoryQuantity(item.quantity, item.material.unit) : item.quantity}`).join(", ")}</span></div>)}{!shipments.length && <p className="py-6 text-center text-sm text-muted-foreground">Henüz sevkiyat yok.</p>}</CardContent></Card>; }
function ConfirmDialog({ open, setOpen, title, description, loading, onConfirm }: { open: boolean; setOpen: (open: boolean) => void; title: string; description: string; loading: boolean; onConfirm: () => Promise<void> }) { return <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>{title}</DialogTitle></DialogHeader><p className="text-sm text-muted-foreground">{description}</p><div className="flex justify-end gap-2"><Button variant="outline" onClick={() => setOpen(false)}>Vazgeç</Button><Button variant="destructive" disabled={loading} onClick={onConfirm}>{loading && <Loader2 className="animate-spin" />}Sil</Button></div></DialogContent></Dialog>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-2"><Label>{label}</Label>{children}</div>; }
function normalizeLines(lines: Line[]) { return lines.filter((line) => line.material_id && Number(line.quantity) > 0).map((line) => ({ material_id: line.material_id, quantity: Number(line.quantity) })); }
