-- =============================================================================
-- 00015 — Geçmiş puantaj, audit, personel istihdam tarihleri ve özetler
-- 00014'ten sonra çalıştırılmalıdır.
-- =============================================================================

alter table public.personnel
  add column if not exists employment_start_date date,
  add column if not exists employment_end_date date;

alter table public.personnel
  drop constraint if exists personnel_employment_dates_valid,
  add constraint personnel_employment_dates_valid check (
    employment_end_date is null
    or employment_start_date is null
    or employment_end_date >= employment_start_date
  ),
  drop constraint if exists personnel_active_end_date_valid,
  add constraint personnel_active_end_date_valid check (
    is_active = false or employment_end_date is null
  );

comment on column public.personnel.employment_start_date is 'İşe giriş tarihi';
comment on column public.personnel.employment_end_date is 'İşten ayrılış tarihi; yalnız pasif personelde kullanılır';

create index if not exists idx_personnel_employment_start
  on public.personnel (employment_start_date);

do $$
begin
  if not exists (
    select 1 from pg_type where typname = 'attendance_leave_type'
  ) then
    create type public.attendance_leave_type as enum (
      'annual',
      'unpaid',
      'excuse',
      'other'
    );
  end if;
end
$$;

alter table public.attendance_records
  add column if not exists leave_type public.attendance_leave_type;

comment on column public.attendance_records.leave_type is
  'Gelecekte izinli durumunun yıllık/ücretsiz/mazeret ayrımı için hazırlanmıştır';

create index if not exists idx_attendance_status
  on public.attendance_records (status);

create table if not exists public.attendance_audit_logs (
  id bigint generated by default as identity primary key,
  attendance_record_id uuid,
  personnel_id uuid not null references public.personnel (id) on delete cascade,
  attendance_date date not null,
  action text not null check (action in ('insert', 'update', 'delete')),
  old_status public.attendance_status,
  new_status public.attendance_status,
  old_leave_type public.attendance_leave_type,
  new_leave_type public.attendance_leave_type,
  changed_by uuid references auth.users (id) on delete set null,
  changed_at timestamptz not null default now()
);

create index if not exists idx_attendance_audit_personnel_date
  on public.attendance_audit_logs (personnel_id, attendance_date, changed_at desc);
create index if not exists idx_attendance_audit_changed_at
  on public.attendance_audit_logs (changed_at desc);

alter table public.attendance_audit_logs enable row level security;
grant select on public.attendance_audit_logs to authenticated;

drop policy if exists "attendance_audit_select_authenticated"
  on public.attendance_audit_logs;
create policy "attendance_audit_select_authenticated"
  on public.attendance_audit_logs for select
  to authenticated using (true);

create or replace function public.log_attendance_change()
returns trigger
language plpgsql
security definer
set search_path = public
set row_security = off
as $$
begin
  if tg_op = 'INSERT' then
    if new.is_auto_generated then
      return new;
    end if;
    insert into public.attendance_audit_logs (
      attendance_record_id, personnel_id, attendance_date, action,
      new_status, new_leave_type, changed_by
    ) values (
      new.id, new.personnel_id, new.attendance_date, 'insert',
      new.status, new.leave_type, auth.uid()
    );
    return new;
  end if;

  if tg_op = 'UPDATE' then
    if old.status is not distinct from new.status
      and old.leave_type is not distinct from new.leave_type then
      return new;
    end if;
    insert into public.attendance_audit_logs (
      attendance_record_id, personnel_id, attendance_date, action,
      old_status, new_status, old_leave_type, new_leave_type, changed_by
    ) values (
      new.id, new.personnel_id, new.attendance_date, 'update',
      old.status, new.status, old.leave_type, new.leave_type, auth.uid()
    );
    return new;
  end if;

  insert into public.attendance_audit_logs (
    attendance_record_id, personnel_id, attendance_date, action,
    old_status, old_leave_type, changed_by
  ) values (
    old.id, old.personnel_id, old.attendance_date, 'delete',
    old.status, old.leave_type, auth.uid()
  );
  return old;
end;
$$;

drop trigger if exists attendance_records_audit
  on public.attendance_records;
create trigger attendance_records_audit
after insert or update or delete on public.attendance_records
for each row execute function public.log_attendance_change();

drop function if exists public.get_monthly_attendance(integer, integer, text, text);

create or replace function public.get_monthly_attendance(
  p_year integer,
  p_month integer,
  p_active_filter text default 'active',
  p_search text default '',
  p_status_filter text default 'all'
)
returns jsonb
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_month_start date;
  v_month_end date;
  v_result jsonb;
begin
  if p_year < 2000 or p_year > 2100 or p_month < 1 or p_month > 12 then
    raise exception 'Geçersiz ay veya yıl';
  end if;
  if p_active_filter not in ('active', 'passive', 'all') then
    raise exception 'Geçersiz personel filtresi';
  end if;
  if p_status_filter not in (
    'all', 'worked', 'absent', 'leave', 'medical_report', 'weekly_rest'
  ) then
    raise exception 'Geçersiz puantaj durum filtresi';
  end if;

  perform public.ensure_sunday_attendance_for_month(p_year, p_month);
  v_month_start := make_date(p_year, p_month, 1);
  v_month_end := (v_month_start + interval '1 month - 1 day')::date;

  with monthly_records as (
    select a.*
    from public.attendance_records a
    where a.attendance_date between v_month_start and v_month_end
      and a.attendance_date <= (now() at time zone 'Europe/Istanbul')::date
  ),
  filtered_personnel as (
    select p.*
    from public.personnel p
    where (
      p_active_filter = 'all'
      or (p_active_filter = 'active' and p.is_active = true)
      or (p_active_filter = 'passive' and p.is_active = false)
    )
    and (
      trim(p_search) = ''
      or p.full_name ilike '%' || trim(p_search) || '%'
      or coalesce(p.phone, '') ilike '%' || trim(p_search) || '%'
    )
    and (
      p_status_filter = 'all'
      or exists (
        select 1 from monthly_records filtered_record
        where filtered_record.personnel_id = p.id
          and filtered_record.status::text = p_status_filter
      )
    )
  ),
  personnel_month as (
    select
      p.id, p.full_name, p.phone, p.is_active,
      p.employment_start_date, p.employment_end_date,
      coalesce(
        jsonb_agg(
          jsonb_build_object(
            'date', to_char(a.attendance_date, 'YYYY-MM-DD'),
            'status', a.status,
            'is_auto_generated', a.is_auto_generated,
            'leave_type', a.leave_type
          ) order by a.attendance_date
        ) filter (where a.id is not null),
        '[]'::jsonb
      ) as records,
      count(a.id) filter (where a.status = 'worked')::integer as worked,
      count(a.id) filter (where a.status = 'absent')::integer as absent,
      count(a.id) filter (where a.status = 'leave')::integer as leave,
      count(a.id) filter (where a.status = 'medical_report')::integer as medical_report,
      count(a.id) filter (where a.status = 'weekly_rest')::integer as weekly_rest
    from filtered_personnel p
    left join monthly_records a on a.personnel_id = p.id
    group by p.id, p.full_name, p.phone, p.is_active,
      p.employment_start_date, p.employment_end_date
  )
  select jsonb_build_object(
    'year', p_year,
    'month', p_month,
    'active_personnel_ids', (
      select coalesce(jsonb_agg(p.id order by p.full_name), '[]'::jsonb)
      from public.personnel p where p.is_active = true
    ),
    'personnel', coalesce(
      jsonb_agg(
        jsonb_build_object(
          'id', id,
          'full_name', full_name,
          'phone', phone,
          'is_active', is_active,
          'employment_start_date', employment_start_date,
          'employment_end_date', employment_end_date,
          'records', records,
          'totals', jsonb_build_object(
            'worked', worked, 'absent', absent, 'leave', leave,
            'medical_report', medical_report, 'weekly_rest', weekly_rest
          )
        ) order by full_name
      ),
      '[]'::jsonb
    )
  ) into v_result
  from personnel_month;

  return v_result;
end;
$$;

revoke execute on function public.get_monthly_attendance(integer, integer, text, text, text)
  from public, anon;
grant execute on function public.get_monthly_attendance(integer, integer, text, text, text)
  to authenticated;

create or replace function public.get_attendance_month_archives()
returns jsonb
language sql
stable
security invoker
set search_path = public
as $$
  with months as (
    select
      date_trunc('month', a.attendance_date)::date as month_start,
      count(*) filter (where a.status = 'worked')::integer as worked,
      count(*) filter (where a.status = 'absent')::integer as absent,
      count(*) filter (where a.status = 'leave')::integer as leave,
      count(*) filter (where a.status = 'medical_report')::integer as medical_report,
      count(*) filter (where a.status = 'weekly_rest')::integer as weekly_rest,
      count(distinct a.attendance_date) filter (
        where a.status = 'worked'
          and extract(isodow from a.attendance_date) = 7
      )::integer as sunday_worked
    from public.attendance_records a
    where a.attendance_date <= (now() at time zone 'Europe/Istanbul')::date
    group by date_trunc('month', a.attendance_date)
  )
  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'year', extract(year from m.month_start)::integer,
        'month', extract(month from m.month_start)::integer,
        'active_personnel', (
          select count(*)::integer
          from public.personnel p
          where coalesce(
            p.employment_start_date,
            (p.created_at at time zone 'Europe/Istanbul')::date
          ) <= (m.month_start + interval '1 month - 1 day')::date
          and (
            p.employment_end_date is null
            or p.employment_end_date >= m.month_start
          )
        ),
        'worked', m.worked,
        'absent', m.absent,
        'leave', m.leave,
        'medical_report', m.medical_report,
        'weekly_rest', m.weekly_rest,
        'sunday_worked', m.sunday_worked
      ) order by m.month_start desc
    ),
    '[]'::jsonb
  )
  from months m;
$$;

revoke execute on function public.get_attendance_month_archives()
  from public, anon;
grant execute on function public.get_attendance_month_archives()
  to authenticated;

create or replace function public.get_personnel_list_summaries(
  p_year integer,
  p_month integer
)
returns jsonb
language sql
stable
security invoker
set search_path = public
as $$
  with limits as (
    select
      make_date(p_year, p_month, 1) as month_start,
      (make_date(p_year, p_month, 1) + interval '1 month - 1 day')::date as month_end,
      make_date(p_year, 1, 1) as year_start,
      make_date(p_year, 12, 31) as year_end,
      (now() at time zone 'Europe/Istanbul')::date as today
  ),
  personnel_summary as (
    select
      p.id as personnel_id,
      p.full_name,
      count(a.id) filter (
        where a.status = 'worked'
          and a.attendance_date between l.month_start and least(l.month_end, l.today)
      )::integer as month_worked,
      count(a.id) filter (
        where a.status = 'absent'
          and a.attendance_date between l.month_start and least(l.month_end, l.today)
      )::integer as month_absent,
      count(a.id) filter (
        where a.status = 'leave'
          and a.attendance_date between l.month_start and least(l.month_end, l.today)
      )::integer as month_leave,
      count(a.id) filter (
        where a.status = 'medical_report'
          and a.attendance_date between l.month_start and least(l.month_end, l.today)
      )::integer as month_medical_report,
      count(a.id) filter (
        where a.status = 'weekly_rest'
          and a.attendance_date between l.month_start and least(l.month_end, l.today)
      )::integer as month_weekly_rest,
      count(a.id) filter (
        where a.status = 'worked'
          and a.attendance_date between l.year_start and least(l.year_end, l.today)
      )::integer as year_worked,
      count(a.id) filter (
        where a.status = 'leave'
          and a.attendance_date between l.year_start and least(l.year_end, l.today)
      )::integer as year_leave,
      count(a.id) filter (
        where a.status = 'medical_report'
          and a.attendance_date between l.year_start and least(l.year_end, l.today)
      )::integer as year_medical_report
    from public.personnel p
    cross join limits l
    left join public.attendance_records a
      on a.personnel_id = p.id
      and a.attendance_date between l.year_start and least(l.year_end, l.today)
    group by p.id, p.full_name
  )
  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'personnel_id', ps.personnel_id,
        'month_worked', ps.month_worked,
        'month_absent', ps.month_absent,
        'month_leave', ps.month_leave,
        'month_medical_report', ps.month_medical_report,
        'month_weekly_rest', ps.month_weekly_rest,
        'year_worked', ps.year_worked,
        'year_leave', ps.year_leave,
        'year_medical_report', ps.year_medical_report
      ) order by ps.full_name
    ),
    '[]'::jsonb
  )
  from personnel_summary ps;
$$;

revoke execute on function public.get_personnel_list_summaries(integer, integer)
  from public, anon;
grant execute on function public.get_personnel_list_summaries(integer, integer)
  to authenticated;

create or replace function public.get_personnel_attendance_detail(
  p_personnel_id uuid,
  p_year integer,
  p_month integer
)
returns jsonb
language sql
stable
security invoker
set search_path = public
as $$
  with limits as (
    select
      make_date(p_year, p_month, 1) as month_start,
      (make_date(p_year, p_month, 1) + interval '1 month - 1 day')::date as month_end,
      make_date(p_year, 1, 1) as year_start,
      make_date(p_year, 12, 31) as year_end,
      (now() at time zone 'Europe/Istanbul')::date as today
  ),
  person_records as (
    select a.*
    from public.attendance_records a
    cross join limits l
    where a.personnel_id = p_personnel_id
      and a.attendance_date <= l.today
  ),
  month_totals as (
    select
      count(*) filter (where status = 'worked')::integer as worked,
      count(*) filter (where status = 'absent')::integer as absent,
      count(*) filter (where status = 'leave')::integer as leave,
      count(*) filter (where status = 'medical_report')::integer as medical_report,
      count(*) filter (where status = 'weekly_rest')::integer as weekly_rest,
      count(*) filter (
        where status = 'worked' and extract(isodow from attendance_date) = 7
      )::integer as sunday_worked
    from person_records r cross join limits l
    where r.attendance_date between l.month_start and least(l.month_end, l.today)
  ),
  year_totals as (
    select
      count(*) filter (where status = 'worked')::integer as worked,
      count(*) filter (where status = 'absent')::integer as absent,
      count(*) filter (where status = 'leave')::integer as leave,
      count(*) filter (where status = 'medical_report')::integer as medical_report,
      count(*) filter (where status = 'weekly_rest')::integer as weekly_rest,
      count(*) filter (
        where status = 'worked' and extract(isodow from attendance_date) = 7
      )::integer as sunday_worked,
      count(*)::integer as total
    from person_records r cross join limits l
    where r.attendance_date between l.year_start and least(l.year_end, l.today)
  ),
  month_distribution as (
    select
      month_number,
      count(r.id) filter (where r.status = 'worked')::integer as worked,
      count(r.id) filter (where r.status = 'leave')::integer as leave,
      count(r.id) filter (where r.status = 'medical_report')::integer as medical_report,
      count(r.id)::integer as total
    from generate_series(1, 12) month_number
    cross join limits l
    left join person_records r
      on extract(month from r.attendance_date) = month_number
      and extract(year from r.attendance_date) = p_year
      and r.attendance_date <= l.today
    group by month_number
  ),
  leave_history as (
    select
      extract(year from attendance_date)::integer as year,
      count(*)::integer as days
    from person_records
    where status = 'leave'
    group by extract(year from attendance_date)
    order by year desc
  )
  select jsonb_build_object(
    'personnel_id', p_personnel_id,
    'year', p_year,
    'month', p_month,
    'month_records', (
      select coalesce(
        jsonb_agg(
          jsonb_build_object(
            'date', to_char(r.attendance_date, 'YYYY-MM-DD'),
            'status', r.status,
            'leave_type', r.leave_type
          ) order by r.attendance_date
        ),
        '[]'::jsonb
      )
      from person_records r cross join limits l
      where r.attendance_date between l.month_start and least(l.month_end, l.today)
    ),
    'month_totals', (select to_jsonb(mt) from month_totals mt),
    'year_totals', (select to_jsonb(yt) from year_totals yt),
    'month_distribution', (
      select jsonb_agg(to_jsonb(md) order by md.month_number)
      from month_distribution md
    ),
    'leave_history', (
      select coalesce(jsonb_agg(to_jsonb(lh) order by lh.year desc), '[]'::jsonb)
      from leave_history lh
    )
  );
$$;

revoke execute on function public.get_personnel_attendance_detail(uuid, integer, integer)
  from public, anon;
grant execute on function public.get_personnel_attendance_detail(uuid, integer, integer)
  to authenticated;
